server:
  port: 8012
#  port:8012:测试负载均衡
spring:
  application:
    name: userprovider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true